# Generated by Django 4.0.2 on 2022-03-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='serves_donats',
            new_name='serves_donuts',
        ),
        migrations.RenameField(
            model_name='waiter',
            old_name='cources',
            new_name='courses',
        ),
    ]
