# Generated by Django 4.0.2 on 2022-02-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
