# Generated by Django 4.0.2 on 2022-03-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_rubric_advertisement_rubric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='rubric',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
