# Generated by Django 4.0.2 on 2022-03-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'permissions': (('can_publish', 'Может публиковать'),), 'verbose_name': 'резюме', 'verbose_name_plural': 'резюме'},
        ),
    ]
